name: Dart and Flutter APK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'

      # Clone the Flutter repository with master channel
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v1
        with:
          channel: 'master'

      # Configure Flutter for macOS desktop
      - name: Configure Flutter for macOS desktop
        run: flutter config --enable-macos-desktop

      # Check Flutter environment
      - name: Check Flutter environment
        run: flutter doctor -v

      # Install Dart dependencies
      - name: Install dependencies
        run: fluuter pub get

      # Analyze Dart project source
      - name: Analyze project source
        run: dart analyze

      # Get Flutter packages
      - name: Get Flutter packages
        run: flutter pub get

      # Build APK
      - name: Build APK
        id: build
        run: flutter build apk --split-per-abi && echo "::set-output name=built-apk::build/app/outputs/flutter-apk/"

      # Upload built APK
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Built APK
          path: ${{ steps.build.outputs.built-apk }}
