name: Flutter Build APK

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - main
    
# on: push    # Default will running for every branch.
env:
  ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE_CONTENTS }}
  
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v4.2.1
    - uses: actions/setup-java@v4.4.0
      with:
        java-version: '17.0.10'
        distribution: 'temurin'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2.16.0
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    # Get flutter dependencies.
    - run: flutter pub upgrade win32
    - run: flutter clean
    - run: flutter pub get

    - name: Set .env file
      run: echo "$ENV_FILE_CONTENTS" > .env
    
    # Build apk.
    - run: flutter build apk --release
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v4.4.3
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
